### ISSUE TITLE
`RawParser` does not implement `Default`

### ISSUE THREAD

**Issue by Mingun** [horazont/rxml#10]
`RawParser` has the parameter-less `new()` method, but it does not implement `Default`. That means that
```rust
type Parser<T> = PullDriver<T, RawParser>;

let mut r = Parser::new("...".as_bytes());
```
does not work, because `PullDriver::new` is implemented only for `Default` parsers

**Comment by horazont** [comment]
I just released 0.8.1 with a fix for this issue. Please feel free to reopen if it still does not work for you.
